proton: ServiceSpec
pipeline:
  dockerfile: Dockerfile
  unit_test_command: echo 'add your unit test command here'
instances:
  - name: development
    environment: development
    spec:
      port: 8080
      desired_count: 2
      task_size: x-small
      image: ykbryan/apprunner-expressjs-app
